prefix:
  plugin: '&7&l[&e&lCFC&7&l]&r'
  development: '&b&l[DEV]&r'
  report: '&c&l[REPORT]&r'
  vote: '&7&l[&9&lVOTE&7&l]&r'
discord:
  prefix: '!'
  token: "token"
  reportchannel: "staff"
  punishementlog: "punishment-log"
tablist:
  header: '✝ &6&lCrafting For Christ Network&r ✝'
  footer: '&6&l/website&r &9&l/discord&r'
web:
  siteaddress: "https://www.craftingforchrist.net/"
  guideaddress: "https://guides.craftingforchrist.net/"
  email: "support@craftingforchrist.net"